SignalK/instrumentpanel

lib/ui/navbar.js

Requires https://github.com/SignalK/signalk-js-client/pull/4

Send 'subscribe all' on connection

---

lib/ui/settings/conversions.js
lib/ui/widgets/universal.js
lib/ui/widgets/windmeter.js

Add windmeter wind speed unit selection

---

lib/ui/widgets/compass.js

Use same widgets for heading and cog, add Digital

---

lib/ui/widgets/compassreadingcomponent.js
lib/ui/widgets/digitalposition.js

More consistent source display

---

lib/ui/widgets/windmeter.js
package-lock.json

Apparent wind angle indicator text field would display current (port) value with 2 decimal places. Modified to display 0 decimal places and added negative value to indicate port (left)

Remove decimal places from Apparent Wind (port)

---

lib/ui/navbar.js

fix: change the cursor type on the heartbeat icon

fix: change the cursor type on the heartbeat icon

---

lib/ui/instrumentpanel.js
lib/ui/main.js

fix: reset displayed sourceId when the page changed

fix: reset displayed sourceId when the page changed

---

lib/ui/instrumentpanel.js

reactivation of knownKeys to reduce additional CPU cycles

fix: reactivation of knownKeys to reduce additional CPU cycles

---

lib/ui/instrumentpanel.js
lib/ui/main.js
lib/ui/widgets/analogcomponent.js
lib/ui/widgets/attitude.js
lib/ui/widgets/compass.js
lib/ui/widgets/compassreadingcomponent.js
lib/ui/widgets/compassrosecomponent.js
lib/ui/widgets/digitalcomponent.js
lib/ui/widgets/universal.js
lib/ui/widgets/windmeter.js

- normalize options passed to the widget
- give access to all options for all widgets
- prepare the notification on widget for path who do not speak

chore: normalize options passed to the widget

---

dist/help/help.md
lib/ui/instrumentpanel.js
lib/ui/main.js

change notification color normal (blue) to same color as nominal (gray)

chore: change notification color normal to same color as nominal

---

lib/util/signalkschemadata.js

hard code some missing metas in Signal K SchemaData

feature: hard code missing metas in Signal K SchemaData

---

dist/help/help.md
lib/ui/instrumentpanel.js
lib/ui/settings/conversions.js
lib/ui/widgets/analogcomponent.js
lib/ui/widgets/basewidget.js
lib/ui/widgets/compass.js
lib/ui/widgets/compassreadingcomponent.js
lib/ui/widgets/compassrosecomponent.js
lib/ui/widgets/digitaldatetime.js
lib/ui/widgets/specifictext.js
lib/ui/widgets/universal.js
lib/ui/widgets/windmeter.js

fixed a bug that caused a white screen when a string was returned instead of a numerical value.

fix: protect rendering against bad value content

---

lib/ui/widgets/analogcomponent.js
lib/ui/widgets/gaugecomponents.js

darker analog hand
- before 
- after

chore: darker analog hand

---

lib/ui/widgets/analogcomponent.js
public/css/instrumentpanel.css

analog gauge with no rounding, thinner line, no shadow....
This PR cannot be used alone, it is part of the preparation for the dark mode.

chore: thinner analog gauge & prepare dark mode

---

lib/ui/widgets/windmeter.js
public/css/instrumentpanel.css

chore: windmeter flat needle shadow-free & prepare dark mode
This PR cannot be used alone, it is part of the preparation for the dark mode.

chore: windmeter flat needle shadow-free & prepare dark mode

---

lib/help/help.md
lib/ui/instrumentpanel.js
lib/ui/navbar.js
package-lock.json
package.json
public/css/instrumentpanel.css

To switch from one page to another, swipe horizontally on the screen.

feature: swipe to change pages

---

lib/ui/settings/conversions.js
lib/ui/widgets/basewidget.js
lib/ui/widgets/digitalcomponent.js

- RPM conversion: Hz => rpm, rpmX100, rpmX1000
- auto resizing units's font: text length > 4 = font size 4 else font size 8

feature: RPM conversion & auto resizing units's font

---

lib/ui/instrumentpanel.js
lib/ui/main.js
lib/ui/settings/settingspanel.js
lib/ui/settings/widgetcell.js
lib/ui/widgets/basewidget.js
lib/ui/widgets/compass.js
lib/ui/widgets/digitaldatetime.js
lib/ui/widgets/digitalposition.js
lib/ui/widgets/specifictext.js
lib/ui/widgets/universal.js
lib/ui/widgets/windmeter.js
package-lock.json

- Reduce the number of pushGridChange calls
- Optimization of writing in localstorage
- Identification of times when the layout must be saved

chore: reduce pushGridChanges calls and optimize localstorage writes

---

lib/ui/widgets/notification.js

chore: optimize notification management

chore: optimize notification management

---

lib/svg/SvgTouchApp24px.js
lib/ui/main.js
lib/ui/widgets/digitaldatetime.js
lib/ui/widgets/digitalposition.js
lib/ui/widgets/windmeter.js
public/css/instrumentpanel.css

- normalization of the widget display mode change call
- preparation of the widget mode in full screen
- fix a future bug on Ipad in webapp mode (avoid z-index: -1 in CSS)

chore: factorise code for widget's changeDisplayMode function

---

lib/ui/settings/saveload.js
lib/util/localstorage.js

fix: load settings from file

---

lib/ui/widgets/attitude.js

fix: missing convert function in attitude widget

---

lib/streambundle.js
lib/ui/widgets/digitalposition.js

Widget digitalposition
Added displayoption DD M.mmmm Dir 
Added to default paths: navigation.courseRhumbline.nextPoint, navigation.courseRhumbline.lastPoint

Feature position options

---

lib/ui/settings/saveload.js

fix: save settings error introduced in #195

---

lib/ui/widgets/analogcomponent.js
lib/ui/widgets/basewidget.js
lib/ui/widgets/digitalcomponent.js

Addition of 2 fixed decimals to display the atmospheric pressure inHg units
fix issue #206

fix: fixed decimal for inHg unit

---

lib/ui/instrumentpanel.js
lib/ui/main.js
lib/ui/navbar.js
lib/ui/settings/constants.js
lib/ui/settings/pathsubscription.js
lib/ui/settings/settingspanel.js
lib/util/localstorage.js

feat:[Path Subscription] option to reduce network bandwidth usage

---

lib/streambundle.js
lib/ui/instrumentpanel.js
lib/ui/navbar.js
lib/ui/settings/constants.js
lib/ui/settings/widgetlist.js
lib/ui/widgets/notification.js
lib/util/localstorage.js
package-lock.json

- added visual alert level setting
- forces `server.newVersion` notification level to `normal` #245

feat: add visual alert level setting

---

lib/ui/instrumentpanel.js
lib/ui/main.js
lib/ui/settings/constants.js
lib/ui/settings/resetsettings.js
lib/ui/settings/saveload.js
lib/ui/widgets/notification.js
lib/util/WidthProvider.jsx

- One layout for portrait mode and another for landscape mode.
- A different layout for each page width.
- Delayed automatic backup (30 seconds) to reduce local writing.
- Local save on close.
- Forces a backup before exporting settings.

feature: different layouts for portrait/landscape mode

---

lib/ui/widgets/universal.js

re-add autoHideLabel accidentally deleted in PR #258

fix: add autoHideLabel accidentally deleted
