SignalK/instrumentpanel

webpack.config.js
Browser WebSocket is always used, so we can safely ignore the `ws` dependency of signalk-client.
=> fix (build): define ws as external

lib/ui/instrumentpanel.js, lib/ui/widgets/basewidget.js, lib/ui/widgets/compass.js, lib/ui/widgets/digitalposition.js, lib/ui/widgets/linear.js, lib/ui/widgets/windmeter.js
Create widgets in multiple columns so that the initial layout is not just a single really long column. 
Widgets are grouped by SK path prefix: the first column is navigation, the second is environment and after that columns are created on the fly, depending on the incoming data.
Resolves #40
=> Create widgets in multiple columns by default

lib/ui/widgets/analogcomponent.js, lib/ui/widgets/digitalcomponent.js, webpack.config.js
With longer SK paths and source names the label was getting really long and ugly. This PR splits the information to two rows.
=> Split path and source label to two rows

dist/css/settingslist.css
Partial fix the bad position of icon on clickable widget in setting mode.
- This solve for chrome browser.
- In firefox browser, icon is simply not displayed  👎
- May be fixed with an update of the React version in the future.
=> fix: bad position of icon on clickable widget in setting mode (chrome browser)

lib/ui/instrumentpanel.js
feature: check outdated widgets before loading layout
- On loading layout, the widget type is checked in the widget database.
- if it's outdated, it's replaced with the new one.
- If it's unknown widget, the universal widget is used.
=> feature: check outdated widgets before loading layout

lib/ui/widgets/windmeter.js
feature: add popup if no wind true data
When you clic on windmeter widget if your system seems to be missing true wind, a popup message is raised to invite the user to try installing the Derived Data plugin, and activating "Ground  Wind Angle" & "Speed True Wind Angle" fonctionallity.
=> feature: add popup if no wind true data

lib/ui/widgets/basewidget.js
chore: add the new widgets by page bottom
To avoid breaking the existing layout, the new discovered widgets are add by page bottom.
=> chore: add the new widgets by page bottom

README.md, lib/ui/main.js
For iOS user:
=============
In `edit mode` for draging or resizing a widget, click one or twice on the center of the widget to get focus on it and after you can drag or resize widget with grid's scroll locked.  
If you don't click before on center of the widget, the grid scroll before you can drag or resize widget.  
For scrolling the grid, it's better to do by the left side even if vertical scroll bar is on the right side.  
In vertical scrolling by the the right side, you risk resizing the widget instead of scrolling the grid.
=> fix: draging & resizing widget on iOS12

index.html, lib/ui/instrumentpanel.js, lib/ui/main.js, lib/ui/navbar.js, lib/ui/settings/settingspanel.js, lib/ui/settings/widgetrow.js, lib/ui/widgets/basewidget.js, lib/ui/widgets/notification.js
- Rewriting toolTips code with a react component.
- When you click on the top right corner of a widget to display the toolTips, the vertical size of the toolTips can now exceed the size of the widget and display more informations.
- Easier management to add content to the toolTips
- Blocking of widget size changes in the notification tab.
- Optimization of widget refresh in case of alarm level change.
- Modification of the widget ID to be unique in all pages (Id => PageNumber-Id).
- Updating the layout format when loading an old one saved configuration.
=> chore: rewriting toolTips code

lib/ui/instrumentpanel.js, lib/ui/widgets/basewidget.js, lib/ui/widgets/specifictext.js
`specificText` is a widget dedicated to signal K paths that return value as json or a long string.
This widget is implemented for the following paths:
- `environment.current`
- `navigation.gnss.methodQuality`
- `navigation.gnss.integrity`
- `navigation.gnss.type`
- `navigation.speedThroughWaterReferenceType`
- `design.length`
- `design.aisShipType`
Adding new paths is simplified:
- Add an entry in the `pathsOptions` array.
- Build the display function.
=> feature: add specific widget

lib/ui/settings/widgetrow.js
fix bad reference in toggleActive() when updateNotificationLevel() or pushGridChanges()
=> fix: updateNotificationLevel & pushGridChanges in toggleActive

lib/ui/instrumentpanel.js
This pull request delays the call to `browser.saveGrid` to avoid repetitive calls.
- Before: for 34 widgets => 35 writes in the local storage at startup.
- After: 1 single call and 1 single writing.
=> chore: reduce the number of browser.saveGrid() calls

dist/help/help.md, lib/ui/instrumentpanel.js, lib/ui/navbar.js, lib/ui/settings/settingspanel.js, lib/ui/widgets/digitaldatetime.js, lib/ui/widgets/specifictext.js, lib/ui/widgets/universal.js, lib/ui/widgets/windmeter.js
When you change the unit on a widget, InstrumentPanel must be reloaded to make the new unit conversion active.
Now this will be done automatically when you leave settings tab.
You will be informed by a message at the top of the screen.
=> feature: auto reload page when unit changed

index.html, lib/ui/settings/settingspanel.js
Fixed a issue to avoid deleting all local storage when you reset the instrumentationpanel configuration.
=> fix: avoid clear entire localstorage

lib/ui/widgets/notification.js
avoid searching for metadata when notification path is discovered
=> chore: avoid searching for notification's meta

dist/help/help.md, lib/ui/widgets/digitalposition.js
The digitalposition widget can now display the following paths :
- navigation.position
- navigation.courseGreatCircle.nextPoint.position
- navigation.courseGreatCircle.previousPoint.position
- navigation.anchor.position
=> feature: extending display capabilities of digitalposition widget

lib/ui/instrumentpanel.js, lib/ui/main.js, lib/ui/widgets/analogcomponent.js, lib/ui/widgets/attitude.js, lib/ui/widgets/compass.js, lib/ui/widgets/digitaldatetime.js, lib/ui/widgets/digitalposition.js, lib/ui/widgets/gaugecomponents.js, lib/ui/widgets/notification.js, lib/ui/widgets/specifictext.js, lib/ui/widgets/universal.js, lib/ui/widgets/windmeter.js, lib/util/browser.js, package-lock.json, package.json, webpack.config.js
Update webpack4 / babel7 to the latest version:
- webpack: 4.27.1 => 4.41.0
- babel:  6.26.3 => 7.6.2
- javascript compatibility ES205+
- some code rewrites to be compatible with babel7
=> chore: Update webpack4 / babel7 to the latest version

lib/ui/widgets/digitaldatetime.js
paths displayed by the digitaldatetime widget :
- navigation.datetime
- environment.tide.timeLow
- environment.tide.timeHigh
- electrical.batteries.*.dateInstalled
- electrical.inverters.*.dateInstalled
- electrical.chargers.*.dateInstalled
- electrical.alternators.*.dateInstalled
- electrical.alternators.*.dateInstalled
=> feature: add additional paths to the digitaldatetime widget

lib/ui/main.js
avoid widget goes to fullscreen in design mode
fix issue #163
=> fix: avoid widget goes to fullscreen in design mode

lib/streambundle.js, lib/ui/instrumentpanel.js, lib/ui/settings/settingspanel.js, lib/ui/settings/widgetcell.js, public/css/instrumentpanel.css
uncheck `Show on grid` on all widgets with a red dotted border in all pages
and replace them by checking the `Show on grid` box on the widget with the right source
=> fix: migrate paths with "no_source" to real source

lib/streambundle.js, lib/ui/instrumentpanel.js, lib/ui/navbar.js, lib/ui/settings/saveload.js, lib/ui/widgets/basewidget.js, lib/util/signalk-client.js
- Correcting for loss of units when preferred units are not fixed
- Avoid the loss of the first meta updates and delta updates at the beginning of the connection
- Improvement of the processing of the connection information
- Creation of preferred units when the server does not provide any
- Added more relevant debugging
=> fix: loss of units when preferred units are not set

lib/ui/instrumentpanel.js, lib/util/signalk-client.js
Sends an empty message to the websocket every 10 seconds when the client does not receive any more update from the server to detect if the socket is dead.
=> fix: better detection of dead websocket

lib/ui/settings/conversions.js, lib/ui/widgets/basewidget.js, lib/ui/widgets/digitaldatetime.js
Celsius and Fahrenheit units were missing the degree mark (°). This has been fixed.
The selection of allowed date formats was IMO arbitrary and limited. It has been fixed to be more internationally representative (although still arbitrary - I tried to cover all common cases I found, though). This was slightly opinionated - I also dropped the two-digit-year variants because I don't think those are the official format in any locale.
=> fix: temperature and date display formats

lib/ui/instrumentpanel.js, lib/util/signalk-client.js, webpack.config.js
Avoid server log message "/loginStatus is deprecated, try updating webapps to the latest version"
=> fix: /loginStatus is deprecated

lib/ui/widgets/basewidget.js
fix: avoid hideLabel checkbox react component switch from uncontrolled to controlled
=> fix: avoid hideLabel checkbox switch from uncontrolled to controlled
